title:
  01-dp: 动态规划
  bag-multi: 多重背包
  bag-tree: 树形背包
  dp-ddp1: 动态动态规划 1
  dp-plug: 插头 dp
  dp-slope: 斜率优化
  02-ds: 数据结构
  balanced-tree: 平衡树
  ds-fhq-treap: 无旋 Treap
  ds-rbtree: 红黑树
  ds-splay: Splay
  ds-treap: Treap
  per-fhq-treap1: 可持久化无旋 Treap 1
  per-fhq-treap2: 可持久化无旋 Treap 2
  ds-odtree: 珂朵莉树
  heap-merge: 可并堆
  linear-basis: 线性基
  link-cut-tree: Link Cut 树
  segment-tree: 线段树
  ds-lc-seg: 李超树
  ds-segtree1: 线段树 1
  ds-segtree2: 线段树 2
  ds-segtree3: 线段树 3
  scanning-line: 扫描线
  sqrt: 根号数据结构
  block-list-1: 块状链表
  block-value: 分块（权值）
  mo-offline-twice: 莫队二次离线
  05-flow: 网络流
  flow-cost: 费用流
  flow-ghtree: 最小割树
  flow-max: 最大流
  flow-range-cost: 上下界费用流
  flow-range-max: 上下界最大流
  09-geometry: 计算几何
  2d: 二维基础
  2d-convex: 二维凸包
  2d-circle: 二维圆形
  2d-lines: 二维线段
  2d-voronoi: Voronoi 图
  2d-delaunay: Delaunay 三角剖分
  2d-hpi: 半平面交
  2d-dynamic-hull: 动态凸包（不支持删除）
  2d-planer-duel: 最左转线
  04-graph: 图论
  cactus: 仙人掌
  count-circle-3: 三元环计数
  count-circle-4: 四元环计数
  graph-base-circle-tree: 基环树
  matching-bipart: 二分图最大匹配
  matching-general: 一般图最大匹配
  dominate-tree: 支配树
  path-johnson: 全源最短路
  tarjan-2sat: 2-SAT
  tarjan-cut-vertex: 割点
  tarjan-edge-ecc: 边双连通分量
  tarjan-point-ecc: 点双连通分量
  tarjan-scc: 强连通分量
  06-math: 数学
  linear: 线性代数
  mat-det: 行列式
  mat-gauss1: 高斯消元与求秩（实数）
  mat-gauss2: 高斯消元与求秩（整数）
  mat-inv: 矩阵求逆
  math-count-graph: 树图计数
  math-bsgs: 大步小步
  math-exgcd: 扩展欧几里得
  math-exexgcd: 万能欧几里得
  math-dirichlet: 狄利克雷前缀和
  math-fast-dlog: 快速离散对数
  math-fast-gcd: 快速最大公约数
  math-genshin: 原根
  math-inv-offline: 快速乘法逆元（离线）
  math-inv-online: 快速乘法逆元（在线）
  math-mod: Barrett 取模
  math-pollards-rho: Pollard's Rho
  math-seive-min25: min25 筛
  math-sieve-du: 杜教筛
  math-sieve-pn: PN 筛
  math-twice: 二次剩余
  math-lagrange: 拉格朗日插值
  math-min-max: min-max 容斥
  math-polya: polya 定理
  math-unit-root: 单位根反演
  math-crt: 中国剩余定理
  10-other: 其他
  cartesian-tree: 笛卡尔树
  cdq: CDQ 分治
  general: 快速读入
  simpson: 自适应辛普森
  simulate-anneal: 模拟退火
  xor-shift: 伪随机生成
  day: 日期公式
  py-hint: Python 技巧
  run: 快速测试
  stress: 对拍脚本
  pbds: pbds 库
  07-poly: 多项式
  poly-family: NTT 全家桶
  poly-fwt: FWT 全家桶
  poly-fwt-short: 定系数短多项式卷积
  poly-mtt: 任意模数 NTT
  poly-bm: 最小多项式
  08-string: 字符串
  acam: AC 自动机
  kmp-ex: 扩展 KMP
  manacher: Manacher
  pam: 回文自动机
  sa-balanced-tree: 后缀平衡树
  sa-mul: 后缀数组（倍增）
  sa-sais: 后缀数组（SAIS）
  sam-general-offline: 广义后缀自动机（离线）
  sam-general-online: 广义后缀自动机（在线）
  sam: 后缀自动机
  trie: 字典树
  03-tree: 树论
  ds-ptree: 点分树
  lca: 最近公共祖先
  tree-divide-length: 长链剖分
  tree-divide-weight: 重链剖分
  tree-hash: 树哈希
  tree-prufer: Prufer 序列
  virtual-tree: 虚树
  header: 公共头文件

wf_files:
  - balanced-tree
  - ds-fhq-treap
  - ds-odtree
  - heap-merge
  - link-cut-tree
  - ds-lc-seg
  - ds-segtree3
  - flow-cost
  - flow-ghtree
  - flow-max
  - flow-range-cost
  - flow-range-max
  - count-circle-3
  - count-circle-4
  - matching-bipart
  - matching-general
  - dominate-tree
  - tarjan-2sat
  - tarjan-cut-vertex
  - tarjan-edge-ecc
  - tarjan-point-ecc
  - tarjan-scc
  - mat-det
  - math-count-graph
  - math-bsgs
  - math-exgcd
  - math-exexgcd
  - math-dirichlet
  - math-fast-dlog
  - math-genshin
  - math-mod
  - math-pollards-rho
  - math-seive-min25
  - math-sieve-du
  - math-twice
  - math-lagrange
  - math-min-max
  - math-polya
  - math-unit-root
  - math-crt
  - cartesian-tree
  - cdq
  - simpson
  - xor-shift
  - py-hint
  - day
  - run
  - stress
  - pbds
  - poly-family
  - poly-fwt
  - poly-fwt-short
  - poly-mtt
  - poly-bm
  - acam
  - kmp-ex
  - pam
  - sa-mul
  - sam-general-offline
  - sam-general-online
  - sam
  - ds-ptree
  - tree-hash
  - tree-prufer
  - virtual-tree
  - 2d
  - 2d-circle
  - 2d-lines
  - 2d-hpi
  - 2d-voronoi
  - 2d-dynamic-hull
  - 2d-delaunay
