site_name: Hourai's Template
site_description: 哈尔滨工业大学蓬莱人形算法程序设计竞赛模板归档
site_author: Hourai Ningyou
site_url: https://hourai.nanani-fan.club
repo_name: DWaveletT/hourai
repo_url: https://github.com/DWaveletT/hourai
theme:
  name: material
  static_templates:
  - 404.html
  language: zh
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: white
    accent: red
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: blue
    accent: blue
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: favicon.ico
  icon:
    logo: material/school
  features:
  - navigation.tabs
  - navigation.instant
  font:
    text: Fira Sans
    code: Fira Mono
extra_javascript:
- javascripts/katex.js
- https://unpkg.com/katex@0/dist/katex.min.js
- https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
- https://unpkg.com/katex@0/dist/katex.min.css
markdown_extensions:
- admonition
- def_list
- footnotes
- meta
- toc:
    permalink: ''
    slugify: !!python/name:pymdownx.slugs.uslugify ''
- pymdownx.arithmatex:
    generic: true
- pymdownx.caret
- pymdownx.critic
- pymdownx.highlight:
    linenums: true
- pymdownx.inlinehilite
- pymdownx.progressbar
- pymdownx.superfences:
    custom_fences:
    - name: math
      class: arithmatex
      format: !!python/name:pymdownx.arithmatex.fence_mathjax_format ''
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
nav:
- 动态规划:
  - 多重背包: bag-multi.md
  - 树形背包: bag-tree.md
  - 动态动态规划 1: dp-ddp1.md
  - 插头 dp: dp-plug.md
  - dp-quad-inequality: dp-quad-inequality.md
  - 斜率优化: dp-slope.md
- 数据结构:
  - 平衡树:
    - 无旋 Treap: ds-fhq-treap.md
    - Splay: ds-splay.md
    - Treap: ds-treap.md
  - 珂朵莉树: ds-odtree.md
  - 可并堆: heap-merge.md
  - 线性基: linear-basis.md
  - Link Cut 树: link-cut-tree.md
  - 线段树:
    - 李超树: ds-lc-seg.md
    - 线段树 3: ds-segtree3.md
    - 扫描线: scanning-line.md
  - 根号数据结构:
    - 块状链表: block-list-1.md
    - 莫队二次离线: mo-offline-twice.md
- 树论:
  - 点分树: ds-ptree.md
  - 长链剖分: tree-divide-length.md
  - 重链剖分: tree-divide-weight.md
  - 树哈希: tree-hash.md
  - tree-intersect: tree-intersect.md
  - Prufer 序列: tree-prufer.md
  - 虚树: virtual-tree.md
- 图论:
  - 仙人掌: cactus.md
  - 三元环计数: count-circle-3.md
  - 四元环计数: count-circle-4.md
  - 支配树: dominate-tree.md
  - 基环树: graph-base-circle-tree.md
  - 二分图最大匹配: matching-bipart.md
  - 一般图最大匹配: matching-general.md
  - 2-SAT: tarjan-2sat.md
  - 割点: tarjan-cut-vertex.md
  - 边双连通分量: tarjan-edge-ecc.md
  - 点双连通分量: tarjan-point-ecc.md
  - 强连通分量: tarjan-scc.md
- 网络流:
  - 费用流: flow-cost.md
  - 最小割树: flow-ghtree.md
  - 最大流: flow-max.md
  - 上下界费用流: flow-range-cost.md
  - 上下界最大流: flow-range-max.md
- 数学:
  - 线性代数:
    - 行列式: mat-det.md
    - 高斯消元与求秩（实数）: mat-gauss1.md
    - 高斯消元与求秩（整数）: mat-gauss2.md
    - 矩阵求逆: mat-inv.md
  - 大步小步: math-bsgs.md
  - 树图计数: math-count-graph.md
  - 中国剩余定理: math-crt.md
  - 狄利克雷前缀和: math-dirichlet.md
  - 万能欧几里得: math-exexgcd.md
  - 扩展欧几里得: math-exgcd.md
  - 快速离散对数: math-fast-dlog.md
  - 快速最大公约数: math-fast-gcd.md
  - 原根: math-genshin.md
  - 快速乘法逆元（离线）: math-inv-offline.md
  - 快速乘法逆元（在线）: math-inv-online.md
  - 拉格朗日插值: math-lagrange.md
  - min-max 容斥: math-min-max.md
  - Barrett 取模: math-mod.md
  - Pollard's Rho: math-pollards-rho.md
  - polya 定理: math-polya.md
  - min25 筛: math-seive-min25.md
  - 杜教筛: math-sieve-du.md
  - PN 筛: math-sieve-pn.md
  - 二次剩余: math-twice.md
  - 单位根反演: math-unit-root.md
- 多项式:
  - 最小多项式: poly-bm.md
  - NTT 全家桶: poly-family.md
  - 定系数短多项式卷积: poly-fwt-short.md
  - FWT 全家桶: poly-fwt.md
  - 任意模数 NTT: poly-mtt.md
- 字符串:
  - AC 自动机: acam.md
  - 扩展 KMP: kmp-ex.md
  - Manacher: manacher.md
  - 回文自动机: pam.md
  - 后缀平衡树: sa-balanced-tree.md
  - 后缀数组（倍增）: sa-mul.md
  - 后缀数组（SAIS）: sa-sais.md
  - 广义后缀自动机（离线）: sam-general-offline.md
  - 广义后缀自动机（在线）: sam-general-online.md
  - 后缀自动机: sam.md
- 计算几何:
  - 二维圆形: 2d-circle.md
  - 二维凸包: 2d-convex.md
  - Delaunay 三角剖分: 2d-delaunay.md
  - 动态凸包（不支持删除）: 2d-dynamic-hull.md
  - 半平面交: 2d-hpi.md
  - 二维线段: 2d-lines.md
  - 最左转线: 2d-planer-duel.md
  - Voronoi 图: 2d-voronoi.md
  - 二维基础: 2d.md
- 其他:
  - 笛卡尔树: cartesian-tree.md
  - CDQ 分治: cdq.md
  - 日期公式: day.md
  - misc: misc.md
  - pbds 库: pbds.md
  - Python 技巧: py-hint.md
  - 快速测试: run.md
  - 自适应辛普森: simpson.md
  - 模拟退火: simulate-anneal.md
  - 对拍脚本: stress.md
  - 伪随机生成: xor-shift.md
- 公共头文件: header.md
