name: Hourai Build
 
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pipenv
      
      - name: Install Python dependencies
        run: |
          pip install pipenv
          pipenv install

      - name: Build
        run: pipenv run mkdocs build -v

  produce:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Convey
        uses: docker://pandoc/extra:3.5.0.0
        with:
          args: ./docs/print/all.md --output=./docs/print/all.pdf --template /.pandoc/templates/eisvogel.latex --listings -V block-headings

  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site