name: Build & Deploy
 
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.12'
      #     cache: pipenv
      
      # - name: Install Python dependencies
      #   run: |
      #     pip install pipenv
      #     pipenv install

      # - name: Build
      #   run: pipenv run mkdocs build -v

      - name: Install Font
        run: |
          wget -O fonts.zip https://github.com/adobe-fonts/source-han-sans/releases/download/2.004R/SourceHanSansHWSC.zip
          unzip fonts.zip
          sudo mkdir fonts
          sudo cp -i OTF/SimplifiedChineseHW/SourceHanSansHWSC-Regular.otf fonts
          sudo cp -i OTF/SimplifiedChineseHW/SourceHanSansHWSC-Bold.otf fonts
          ls fonts

      - name: Convey
        uses: docker://pandoc/extra:3.5.0.0
        with:
          args: docs/print/all.md --output=site/print/all.pdf --template /.pandoc/templates/eisvogel.latex --pdf-engine=xelatex --listings -V block-headings -V lang=zh-CN -V CJKmainfont="SourceHanSansHWSC-Regular.otf"

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v4
      #   if: github.ref == 'refs/heads/master'
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./site