name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 缓存 apt 包
      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: |
            /var/lib/apt/lists
            /var/cache/apt/archives
          key: ${{ runner.os }}-apt-texlive
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Update apt
        run: sudo apt-get update

      # 安装最小 TeX Live
      - name: Install TeX Live (minimal)
        run: |
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-xetex \
            texlive-lang-chinese \
            texlive-fonts-recommended \
            texlive-science \
            lmodern \
            latexmk pandoc

      # 缓存 TeX Live 用户配置（字体缓存等）
      - name: Cache TeX Live cache
        uses: actions/cache@v4
        with:
          path: ~/.texlive*
          key: ${{ runner.os }}-texlive-cache

      # 安装 Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pipenv'

      # 下载 Mkdocs 以及相关依赖
      - name: Set up Mkdocs
        run: |
          pipenv install
        
      # 调用 Python 脚本构建 MD
      - name: Build Markdown
        run: pipenv run python scripts/build_docs.py

      # 调用 Python 脚本构建 PDF
      - name: Build PDF
        run: pipenv run python scripts/build_print.py

      # 使用 MkDocs 构建网站
      - name: Build Web
        run: mkdocs build

      # 部署到 Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
