name: Build and Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create TeX Live deps file
        run: |
          echo "texlive-latex-base texlive-latex-recommended texlive-xetex texlive-lang-chinese texlive-fonts-recommended texlive-science lmodern latexmk pandoc" > scripts/texlive-deps.txt

      # 缓存 apt 包和 TeX Live
      - name: Cache TeX Live and apt packages
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt/archives
            /usr/share/texlive
            /var/lib/texmf
          key: ${{ runner.os }}-texlive-apt-${{ hashFiles('scripts/texlive-deps.txt') }}
          restore-keys: |
            ${{ runner.os }}-texlive-apt-

      - name: Update apt
        run: sudo apt-get update

      - name: Install TeX Live deps
        run: |
          sudo apt-get install -y $(cat scripts/texlive-deps.txt)

      # 修复 restore 后的权限
      - name: Fix TeX Live permissions
        run: |
          sudo chown -R $USER:$USER /usr/share/texlive /var/lib/texmf

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pipenv'

      - name: Set up Mkdocs
        run: |
          pip install pipenv
          pipenv install

      - name: Build Markdown
        run: pipenv run python scripts/build_docs.py

      - name: Build PDF
        run: pipenv run python scripts/build_print.py

      - name: Build Web
        run: |
          pipenv run mkdocs build
          ls -R ./site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
